# Base configs
baseurl: ""
url: "https://agebeyaw.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-55682111-1"

# UI configs
title: "Photography by Mesfin Adugna"
subtitle: "See the world through my eyes!"
author: "Mesfin Adugna"
bio: "Mesfin Adugna |  Ethiographics Photography."
publicise: "Want a website like this for yourself for free? Just send an email to <a mailto=\"antenehgeb@gmail.com\">antenehgeb@gmail.com</a> ;)"
web_design: "Anteneh Gebeyaw"
social_urls:
  facebook: "https://www.facebook.com/Ethiographics-Photography-384642142808/"
  twitter: "https://twitter.com/angeboy"
  instagram: "https://www.instagram.com/ethiographics/"
  
